# Generated by Django 2.2.4 on 2021-08-16 00:44

from django.db import migrations, models
import podomarket.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0003_auto_20210815_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=40, null=True, validators=[podomarket.validators.no_special_character]),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(max_length=20, null=True, validators=[podomarket.validators.no_special_character]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임'}, max_length=15, null=True, unique=True, validators=[podomarket.validators.no_special_character]),
        ),
    ]
